# Generated by Django 6.1 on 2026-08-30 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Dairy Product', 'verbose_name_plural': 'Dairy Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('milk', 'Milk (Pasteurized / Raw)'), ('curd', 'Curd & Yogurt'), ('butter', 'Butter'), ('ghee', 'Ghee'), ('paneer', 'Paneer'), ('cheese', 'Cheese'), ('ice_cream', 'Ice Cream'), ('flavoured_milk', 'Flavoured Milk'), ('other', 'Other Products')], default='milk', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit Production/Purchase Cost (₹)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10, help_text='Minimum threshold for low stock alert'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('liter', 'Liter (L)'), ('packet_500ml', '500ml Packet'), ('packet_1l', '1 Liter Packet'), ('kg', 'Kilogram (Kg)'), ('pouch_200g', '200g Pouch'), ('can_5l', '5 Liter Can'), ('jar_500g', '500g Jar'), ('box', 'Box / Pack')], default='packet_500ml', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Unit Selling Price (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock units'),
        ),
    ]
